[build-system]
requires = ["setuptools>=45", "wheel", "pip>=21.0"]
build-backend = "setuptools.build_meta"

[project]
name = "comic_translator"
version = "0.1.0"
description = "A tool for translating comic book pages"
requires-python = ">=3.10,<3.12"